title: Romain Desarzens
description: >-
  Senior Robotics Engineer | Motion Planning & Control | ROS, C++, Python, Rust
baseurl: ""
url: "https://rdesarz.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
